const fs = require('fs');
const path = require('path');
const file = path.join(__dirname, '..', 'data', 'recipes.json');
const existing = JSON.parse(fs.readFileSync(file, 'utf-8'));
const more = [
  {name:'红烧蹄髈',category:'荤菜',cuisine:'家常菜',difficulty:3,cook_time:120,servings:4,ingredients:[{name:'猪蹄',amount:'2只'},{name:'冰糖',amount:'50g'},{name:'生抽',amount:'4勺'},{name:'老抽',amount:'2勺'}],steps:['猪蹄焯水','炒糖色','下猪蹄翻炒上色','加调料、热水炖2小时'],tags:['硬菜','下饭','宴客'],tips:'炖的时间要够',image:'\uD83D\uDC16'},
  {name:'猪蹄花生汤',category:'汤',cuisine:'家常菜',difficulty:2,cook_time:120,servings:4,ingredients:[{name:'猪蹄',amount:'1只'},{name:'花生',amount:'100g'},{name:'姜',amount:'3片'},{name:'盐',amount:'适量'}],steps:['猪蹄焯水','加花生、姜、热水','炖2小时','加盐调味'],tags:['汤','养生','下奶'],tips:'花生要提前泡',image:'\uD83E\uDD5C'},
  {name:'红烧鸡爪',category:'荤菜',cuisine:'家常菜',difficulty:2,cook_time:40,servings:3,ingredients:[{name:'鸡爪',amount:'500g'},{name:'生抽',amount:'3勺'},{name:'老抽',amount:'1勺'},{name:'冰糖',amount:'30g'}],steps:['鸡爪剪指甲焯水','炒糖色','下鸡爪翻炒','加调料、热水炖30分钟收汁'],tags:['下饭','下酒','硬菜'],tips:'炒糖色要注意火候',image:'\uD83D\uDC14'},
  {name:'卤鸡爪',category:'凉菜',cuisine:'家常菜',difficulty:2,cook_time:30,servings:3,ingredients:[{name:'鸡爪',amount:'500g'},{name:'卤料包',amount:'1份'},{name:'生抽',amount:'50ml'}],steps:['鸡爪焯水','卤水烧开下鸡爪','小火卤20分钟','关火浸泡1小时'],tags:['下酒','凉菜','硬菜'],tips:'卤水越老越好',image:'\uD83D\uDC14'},
  {name:'爆炒腰花',category:'荤菜',cuisine:'川菜',difficulty:3,cook_time:15,servings:2,ingredients:[{name:'猪腰',amount:'2个'},{name:'泡椒',amount:'适量'},{name:'生抽',amount:'2勺'},{name:'料酒',amount:'1勺'}],steps:['腰子处理干净切花','用料酒腌10分钟','热油爆香泡椒','下腰花大火快炒','加生抽翻匀出锅'],tags:['川菜','下饭','硬菜'],tips:'火要大炒得要快',image:'\uD83D\uDC16'},
  {name:'溜肝尖',category:'荤菜',cuisine:'东北菜',difficulty:3,cook_time:15,servings:2,ingredients:[{name:'猪肝',amount:'300g'},{name:'青椒',amount:'2个'},{name:'胡萝卜',amount:'1根'},{name:'生抽',amount:'2勺'}],steps:['肝切片用生抽、淀粉腌10分钟','青椒胡萝卜切片','热油滑熟肝片盛出','锅内爆香葱姜','下肝片、配菜翻匀'],tags:['东北菜','下饭','硬菜'],tips:'肝要炒嫩一点',image:'\uD83D\uDC16'},
  {name:'蒜薹炒肉',category:'荤菜',cuisine:'家常菜',difficulty:1,cook_time:15,servings:2,ingredients:[{name:'蒜薹',amount:'300g'},{name:'猪肉',amount:'200g'},{name:'生抽',amount:'2勺'}],steps:['蒜薹切段','猪肉切丝','热油爆香肉丝','下蒜薹、调料翻匀'],tags:['下饭','家常','简单'],tips:'蒜薹要选嫩的',image:'\uD83E\uDDC4'},
  {name:'农家小炒肉',category:'荤菜',cuisine:'湘菜',difficulty:2,cook_time:15,servings:2,ingredients:[{name:'五花肉',amount:'300g'},{name:'青椒',amount:'3个'},{name:'豆鼓',amount:'适量'},{name:'生抽',amount:'2勺'}],steps:['五花肉切薄片','青椒切块','热油煸炒肉片出油','下豆鼓、青椒、生抽翻匀'],tags:['湘菜','下饭','香辣'],tips:'肉要煸出油才香',image:'\uD83C\uDF36'},
  {name:'湖南腊味合蒸',category:'荤菜',cuisine:'湘菜',difficulty:2,cook_time:30,servings:3,ingredients:[{name:'腊肉',amount:'200g'},{name:'腊鱼',amount:'200g'},{name:'腊鸡',amount:'200g'},{name:'豆鼓',amount:'适量'}],steps:['腊味切块洗净','装碗加豆鼓','大火蒸20分钟'],tags:['湘菜','下饭','传统'],tips:'腊味要先泡软',image:'\uD83E\uDD53'},
  {name:'板鸭蒸豆腐',category:'荤菜',cuisine:'家常菜',difficulty:2,cook_time:20,servings:2,ingredients:[{name:'板鸭',amount:'200g'},{name:'嫩豆腐',amount:'1盒'},{name:'姜',amount:'适量'}],steps:['板鸭切块','豆腐切块','铺板鸭和豆腐','大火蒸15分钟'],tags:['下饭','简单','咸香'],tips:'板鸭有盐不用加',image:'\uD83E\uDD86'},
  {name:'香菇鸡汤',category:'汤',cuisine:'家常菜',difficulty:1,cook_time:60,servings:4,ingredients:[{name:'三黄鸡',amount:'半只'},{name:'香菇',amount:'5朵'},{name:'红枣',amount:'5颗'},{name:'姜',amount:'3片'}],steps:['鸡块焯水','加香菇、红枣、姜、热水','炖1小时','加盐调味'],tags:['汤','养生','家常'],tips:'小火慢炖才香',image:'\uD83C\uDF57'},
  {name:'木耳炒鸡蛋',category:'素菜',cuisine:'家常菜',difficulty:1,cook_time:10,servings:2,ingredients:[{name:'木耳',amount:'100g'},{name:'鸡蛋',amount:'3个'},{name:'葱花',amount:'适量'},{name:'盐',amount:'适量'}],steps:['木耳泡发焯水','鸡蛋炒熟盛出','热油下木耳翻炒','加鸡蛋、葱花、盐'],tags:['简单','下饭','家常'],tips:'木耳要选东北黑木耳',image:'\uD83C\uDF44'},
  {name:'丝瓜炒蛋',category:'素菜',cuisine:'家常菜',difficulty:1,cook_time:10,servings:2,ingredients:[{name:'丝瓜',amount:'2根'},{name:'鸡蛋',amount:'3个'},{name:'盐',amount:'适量'}],steps:['丝瓜去皮切片','鸡蛋炒熟盛出','热油下丝瓜炒软','加鸡蛋翻匀加盐'],tags:['简单','下饭','家常'],tips:'丝瓜要保持翠绿',image:'\uD83E\uDD52'},
  {name:'金针菇炒蛋',category:'素菜',cuisine:'家常菜',difficulty:1,cook_time:10,servings:2,ingredients:[{name:'金针菇',amount:'200g'},{name:'鸡蛋',amount:'3个'},{name:'葱花',amount:'适量'},{name:'盐',amount:'适量'}],steps:['金针菇切段焯水','鸡蛋炒熟盛出','热油下金针菇翻炒','加鸡蛋、葱花、盐'],tags:['简单','下饭','家常'],tips:'金针菇要焯水去腥',image:'\uD83C\uDF44'},
  {name:'五香花生米',category:'凉菜',cuisine:'家常菜',difficulty:1,cook_time:15,servings:3,ingredients:[{name:'花生米',amount:'300g'},{name:'八角',amount:'2个'},{name:'花椒',amount:'10粒'},{name:'盐',amount:'适量'}],steps:['花生米洗净','加水、八角、花椒、盐煮10分钟','捞出沥干'],tags:['下酒','凉菜','简单'],tips:'煮好要沥干才能香',image:'\uD83E\uDD5C'},
  {name:'盐水毛豆',category:'凉菜',cuisine:'家常菜',difficulty:1,cook_time:15,servings:3,ingredients:[{name:'毛豆',amount:'500g'},{name:'八角',amount:'2个'},{name:'花椒',amount:'10粒'},{name:'盐',amount:'适量'}],steps:['毛豆剪两头洗净','加水、八角、花椒、盐煮10分钟','捞出沥干'],tags:['下酒','凉菜','简单'],tips:'剪两头更入味',image:'\uD83C\uDF31'},
  {name:'水煮牛肉',category:'荤菜',cuisine:'川菜',difficulty:3,cook_time:25,servings:4,ingredients:[{name:'牛里脊',amount:'300g'},{name:'豆芽',amount:'200g'},{name:'郫县豆瓣',amount:'3勺'},{name:'干辣椒',amount:'20g'}],steps:['牛肉切片用生抽、淀粉腌10分钟','豆芽焯水铺底','锅内炒香豆瓣加水烧开','下牛肉煮熟','浇热油花椒辣椒'],tags:['川菜','麻辣','硬菜'],tips:'油温要高才能激香',image:'\uD83D\uDC04'},
  {name:'啤酒鱼',category:'荤菜',cuisine:'家常菜',difficulty:2,cook_time:25,servings:3,ingredients:[{name:'草鱼',amount:'1条'},{name:'啤酒',amount:'1罐'},{name:'番茄',amount:'1个'},{name:'生抽',amount:'2勺'}],steps:['鱼切块煎至金黄','热油爆香姜蒜','下番茄炒出汁','加啤酒、调料、热水','煮15分钟收汁'],tags:['下饭','啤酒香','硬菜'],tips:'啤酒代替料酒更香',image:'\uD83D\uDC1F'},
  {name:'砂锅豆腐',category:'素菜',cuisine:'家常菜',difficulty:1,cook_time:15,servings:2,ingredients:[{name:'老豆腐',amount:'1盒'},{name:'白菜',amount:'200g'},{name:'粉条',amount:'50g'},{name:'生抽',amount:'2勺'}],steps:['白菜铺底','铺豆腐、粉条','加调料和高汤','砂锅焖10分钟'],tags:['家常','下饭','简单'],tips:'砂锅保温更好',image:'\uD83E\uDDC8'},
  {name:'砂锅鸡',category:'荤菜',cuisine:'家常菜',difficulty:2,cook_time:30,servings:3,ingredients:[{name:'三黄鸡',amount:'半只'},{name:'香菇',amount:'5朵'},{name:'土豆',amount:'2个'},{name:'生抽',amount:'3勺'}],steps:['鸡块焯水','砂锅铺菜放鸡块','加调料和高汤','小火焖25分钟'],tags:['下饭','汤鲜','硬菜'],tips:'砂锅保温锁鲜',image:'\uD83C\uDF57'},
  {name:'炸酱拌面',category:'主食',cuisine:'家常菜',difficulty:1,cook_time:20,servings:2,ingredients:[{name:'面条',amount:'200g'},{name:'肉末',amount:'100g'},{name:'黄豆酱',amount:'3勺'}],steps:['肉末炒香加黄豆酱','加水煮5分钟','煮面浇酱拌匀'],tags:['主食','简单','北方'],tips:'酱要炒香',image:'\uD83C\uDF5C'},
  {name:'葱烧排骨',category:'荤菜',cuisine:'家常菜',difficulty:2,cook_time:40,servings:3,ingredients:[{name:'排骨',amount:'500g'},{name:'大葱',amount:'2根'},{name:'生抽',amount:'3勺'}],steps:['排骨焯水','煎至两面金黄','加大葱、调料、热水','炖30分钟收汁'],tags:['下饭','葱香','硬菜'],tips:'大葱要多才香',image:'\uD83C\uDF56'},
  {name:'红焖羊肉',category:'荤菜',cuisine:'西北菜',difficulty:3,cook_time:120,servings:4,ingredients:[{name:'羊肉',amount:'500g'},{name:'胡萝卜',amount:'2根'},{name:'洋葱',amount:'1个'},{name:'生抽',amount:'3勺'}],steps:['羊肉焯水切块','热油爆香葱姜','下羊肉翻炒','加胡萝卜、洋葱、调料、热水','炖1.5小时'],tags:['西北菜','下饭','硬菜'],tips:'要小火慢炖',image:'\uD83D\uDC11'},
  {name:'手撕包菜',category:'素菜',cuisine:'川菜',difficulty:1,cook_time:10,servings:2,ingredients:[{name:'包菜',amount:'半颗'},{name:'干辣椒',amount:'5个'},{name:'生抽',amount:'2勺'},{name:'醋',amount:'1勺'}],steps:['包菜撕小块','热油爆香干辣椒','下包菜大火快炒','加生抽醋翻匀'],tags:['川菜','下饭','香辣'],tips:'大火快炒',image:'\uD83E\uDD6C'},
  {name:'虎皮鸡蛋',category:'素菜',cuisine:'家常菜',difficulty:1,cook_time:20,servings:3,ingredients:[{name:'鸡蛋',amount:'6个'},{name:'生抽',amount:'3勺'},{name:'老抽',amount:'1勺'},{name:'糖',amount:'1勺'}],steps:['鸡蛋煮熟剥壳','油锅煎至表面起虎皮斑','加调料和少量水焖10分钟'],tags:['下饭','下酒','简单'],tips:'要小火慢煎',image:'\uD83E\uDD5A'},
  {name:'蒜蓉蒸丝瓜',category:'素菜',cuisine:'粤菜',difficulty:1,cook_time:10,servings:2,ingredients:[{name:'丝瓜',amount:'2根'},{name:'蒜末',amount:'30g'},{name:'生抽',amount:'2勺'}],steps:['丝瓜去皮切段','铺蒜末','浇生抽','大火蒸8分钟'],tags:['粤菜','清淡','简单'],tips:'蒜要多',image:'\uD83E\uDD52'}
];
existing.push(...more);
fs.writeFileSync(file, JSON.stringify(existing, null, 0));
console.log('Total recipes:', existing.length);
